### ISSUE TITLE
Hubble loses the FQDN reference after a few moments after it is resolved

### ISSUE THREAD

**Issue by rooque** [cilium/hubble#1438]
I'm having some strange behavior with FQDN destination in Hubble. I have 2 FQDNs, that 2 pods connects :

```
redis.sandbox.whitelabel.com.br
db.sandbox.whitelabel.com.br
```

At first, the FQDN appears both in the service map and in the list correctly. After a few moments, it starts treating the FQDNs' IPs as "world". (see images)

<details><summary>Images</summary>
<p>

<img width="1744" alt="Captura de Tela 2024-03-28 às 15 36 20" src="https://github.com/cilium/hubble/assets/8527149/f61d0c3a-0a93-418a-b598-6f2b00026065">
<img width="1744" alt="Captura de Tela 2024-03-28 às 15 30 07" src="https://github.com/cilium/hubble/assets/8527149/5d86dc04-155a-4d7c-ad9a-205666018991">
<img width="1744" alt="Captura de Tela 2024-03-28 às 15 29 09" src="https://github.com/cilium/hubble/assets/8527149/6a30638e-0b90-48bf-b564-414571f9780a">
<img width="1744" alt="Captura de Tela 2024-03-28 às 15 28 58" src="https://github.com/cilium/hubble/assets/8527149/e9d58303-875f-45af-a668-92aa0dd74475">
<img width="691" alt="Captura de Tela 2024-03-28 às 15 28 17" src="https://github.com/cilium/hubble/assets/8527149/fa307c3d-61c8-4d59-a100-579cdf4393a6">

</p>
</details> 

The problem is not just in the UI, in the CLI is the same

```
Apr  2 15:56:45.180: services/poc-bff-66f46654c-7565m:45148 (ID:103419) -> redis.sandbox.whitelabel.com.br:6379 (ID:16777220) to-stack FORWARDED (TCP Flags: ACK)
Apr  2 15:56:45.180: services/poc-bff-66f46654c-7565m:45148 (ID:103419) <- redis.sandbox.whitelabel.com.br:6379 (ID:16777220) to-endpoint FORWARDED (TCP Flags: ACK)
Apr  2 15:56:49.724: services/poc-microservice-595c9fb49b-gcwvh:58090 (ID:82048) -> redis.sandbox.whitelabel.com.br:6379 (ID:16777220) to-stack FORWARDED (TCP Flags: ACK)
Apr  2 15:56:49.724: services/poc-microservice-595c9fb49b-gcwvh:58090 (ID:82048) <- redis.sandbox.whitelabel.com.br:6379 (ID:16777220) to-endpoint FORWARDED (TCP Flags: ACK)
Apr  2 15:57:05.276: services/poc-bff-66f46654c-7565m:45148 (ID:103419) -> redis.sandbox.whitelabel.com.br:6379 (ID:16777220) to-stack FORWARDED (TCP Flags: ACK)
Apr  2 15:57:05.276: services/poc-bff-66f46654c-7565m:45148 (ID:103419) <- redis.sandbox.whitelabel.com.br:6379 (ID:16777220) to-endpoint FORWARDED (TCP Flags: ACK)

But after some time (30 seconds):

Apr  2 15:57:40.028: services/poc-microservice-595c9fb49b-gcwvh:58090 (ID:82048) -> 10.6.132.252:6379 (ID:16777220) to-stack FORWARDED (TCP Flags: ACK)
Apr  2 15:57:40.028: services/poc-bff-66f46654c-7565m:45148 (ID:103419) -> 10.6.132.252:6379 (ID:16777220) to-stack FORWARDED (TCP Flags: ACK)
Apr  2 15:57:40.028: services/poc-microservice-595c9fb49b-gcwvh:58090 (ID:82048) <- 10.6.132.252:6379 (ID:16777220) to-endpoint FORWARDED (TCP Flags: ACK)
Apr  2 15:57:40.028: services/poc-bff-66f46654c-7565m:45148 (ID:103419) <- 10.6.132.252:6379 (ID:16777220) to-endpoint FORWARDED (TCP Flags: ACK)
```

 NetworkPolicy
 
 ```yaml
 apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: bff-rule
  namespace: services
spec:
  endpointSelector:
    matchLabels:
      app: poc-bff
  ingress:
    - fromEndpoints:
        - {}
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: envoy-gateway-system
  egress:
    - toEndpoints:
        - {}
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: observability
    - toFQDNs:
        - matchPattern: "*.sandbox.whitelabel.com.br"
 ```
 
 The FQDNs shows in this lists, always even after it starting showing as WORLD
 
 ```
 # cilium-dbg fqdn cache list
Endpoint   Source       FQDN                               TTL   ExpirationTime             IPs            
1117       connection   redis.sandbox.whitelabel.com.br.   0     2024-04-02T14:16:09.553Z   10.6.132.252   
1459       connection   redis.sandbox.whitelabel.com.br.   0     2024-04-02T14:16:09.553Z   10.6.132.252   
1459       connection   db.sandbox.whitelabel.com.br.      0     2024-04-02T14:16:09.553Z   10.45.48.3 
```

Also: Every time I restart the pods, I shows the FQDNs for a very short time... Then it start showing as World again.

<details><summary>Cilium Config</summary>
<p>

Client: 1.15.2 7cf57829 2024-03-13T15:34:43+02:00 go version go1.21.8 linux/amd64
Daemon: 1.15.2 7cf57829 2024-03-13T15:34:43+02:00 go version go1.21.8 linux/amd64

```yaml
  agent-not-ready-taint-key: node.cilium.io/agent-not-ready
  arping-refresh-period: 30s
  auto-direct-node-routes: 'false'
  bpf-lb-acceleration: disabled
  bpf-lb-external-clusterip: 'false'
  bpf-lb-map-max: '65536'
  bpf-lb-sock: 'false'
  bpf-map-dynamic-size-ratio: '0.0025'
  bpf-policy-map-max: '16384'
  bpf-root: /sys/fs/bpf
  cgroup-root: /run/cilium/cgroupv2
  cilium-endpoint-gc-interval: 5m0s
  cluster-id: '1'
  cluster-name: gke-1
  cni-exclusive: 'true'
  cni-log-file: /var/run/cilium/cilium-cni.log
  controller-group-metrics: write-cni-file sync-host-ips sync-lb-maps-with-k8s-services
  custom-cni-conf: 'false'
  debug: 'false'
  debug-verbose: ''
  dnsproxy-enable-transparent-mode: 'true'
  egress-gateway-reconciliation-trigger-interval: 1s
  enable-auto-protect-node-port-range: 'true'
  enable-bgp-control-plane: 'false'
  enable-bpf-clock-probe: 'false'
  enable-endpoint-health-checking: 'true'
  enable-endpoint-routes: 'true'
  enable-envoy-config: 'true'
  enable-external-ips: 'false'
  enable-health-check-loadbalancer-ip: 'true'
  enable-health-check-nodeport: 'true'
  enable-health-checking: 'true'
  enable-host-port: 'false'
  enable-hubble: 'true'
  enable-hubble-open-metrics: 'true'
  enable-ipv4: 'true'
  enable-ipv4-big-tcp: 'false'
  enable-ipv4-masquerade: 'true'
  enable-ipv6: 'false'
  enable-ipv6-big-tcp: 'false'
  enable-ipv6-masquerade: 'true'
  enable-k8s-networkpolicy: 'true'
  enable-k8s-terminating-endpoint: 'true'
  enable-l2-neigh-discovery: 'true'
  enable-l7-proxy: 'true'
  enable-local-redirect-policy: 'false'
  enable-masquerade-to-route-source: 'false'
  enable-metrics: 'true'
  enable-node-port: 'false'
  enable-policy: default
  enable-remote-node-identity: 'true'
  enable-sctp: 'false'
  enable-svc-source-range-check: 'true'
  enable-vtep: 'false'
  enable-well-known-identities: 'false'
  enable-wireguard: 'true'
  enable-xt-socket-fallback: 'true'
  external-envoy-proxy: 'true'
  hubble-disable-tls: 'false'
  hubble-export-file-max-backups: '5'
  hubble-export-file-max-size-mb: '10'
  hubble-listen-address: ':4244'
  hubble-metrics: >-
    dns drop tcp flow port-distribution icmp
    httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction
  hubble-metrics-server: ':9965'
  hubble-socket-path: /var/run/cilium/hubble.sock
  hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
  hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
  hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
  identity-allocation-mode: crd
  identity-gc-interval: 15m0s
  identity-heartbeat-timeout: 30m0s
  install-no-conntrack-iptables-rules: 'false'
  ipam: kubernetes
  ipam-cilium-node-update-rate: 15s
  ipv4-native-routing-cidr: 10.0.0.0/18
  k8s-client-burst: '20'
  k8s-client-qps: '10'
  kube-proxy-replacement: 'false'
  kube-proxy-replacement-healthz-bind-address: ''
  loadbalancer-l7: envoy
  loadbalancer-l7-algorithm: round_robin
  loadbalancer-l7-ports: ''
  max-connected-clusters: '255'
  mesh-auth-enabled: 'true'
  mesh-auth-gc-interval: 5m0s
  mesh-auth-queue-size: '1024'
  mesh-auth-rotated-identities-queue-size: '1024'
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  node-port-bind-protection: 'true'
  nodes-gc-interval: 5m0s
  operator-api-serve-addr: 127.0.0.1:9234
  operator-prometheus-serve-addr: ':9963'
  policy-cidr-match-mode: ''
  preallocate-bpf-maps: 'false'
  procfs: /host/proc
  prometheus-serve-addr: ':9962'
  proxy-connect-timeout: '2'
  proxy-max-connection-duration-seconds: '0'
  proxy-max-requests-per-connection: '0'
  remove-cilium-node-taints: 'true'
  routing-mode: native
  service-no-backend-response: reject
  set-cilium-is-up-condition: 'true'
  set-cilium-node-taints: 'true'
  sidecar-istio-proxy-image: cilium/istio_proxy
  skip-cnp-status-startup-clean: 'false'
  synchronize-k8s-nodes: 'true'
  tofqdns-dns-reject-response-code: refused
  tofqdns-enable-dns-compression: 'true'
  tofqdns-endpoint-max-ip-per-hostname: '50'
  tofqdns-idle-connection-grace-period: 0s
  tofqdns-max-deferred-connection-deletes: '10000'
  tofqdns-proxy-response-max-delay: 100ms
  unmanaged-pod-watcher-interval: '15'
  vtep-cidr: ''
  vtep-endpoint: ''
  vtep-mac: ''
  vtep-mask: ''
  wireguard-persistent-keepalive: 0s
  write-cni-conf-when-ready: /host/etc/cni/net.d/05-cilium.conflist
```

</p>
</details> 

<details><summary>SysDump</summary>
<p>

[cilium-sysdump-20240403-174046.zip](https://github.com/cilium/hubble/files/14858310/cilium-sysdump-20240403-174046.zip)

</p>
</details>
