### ISSUE TITLE
CoreDNS stops working when activating Hubble

### ISSUE THREAD

**Issue by bashilias** [cilium/hubble#1630]
Hi, I'm not sure if this is the right repository to create this issue in, however I would like to explain my current situation.
I have a RKE2 downstream running and I'm using Cilium as CNI. Cilium config has been deployed using a HelmChartConfig, all policies are being enforced and it's working fine. 

However, the moment I active Hubble by changing policyAuditMode to 'true', all outgoing traffic are being 'dropped'. Every query in the CoreDNS pods are failed. I wil get a timeout. I also tried to activarte Hubble by opening port 4244 on all nodes for Hubble.

The strange thing is that with both methods Hubble works. The hubble pods and services are being deployed and I can access the Hubble UI. However all outgoing connections within the cluster seems to be 'dropped', every query in CoreDNS gets a timeout.

Anybody has any ideas? Is this a bug or a feature, can Hubble be used while policies are being enforced in the first place?

Method 1 to activate Hubble (helmchartconfig):

```
policyEnforcementMode: always
    policyAuditMode: TRUE
    hostFirewall:
      enabled: true
    image:
      pullPolicy: IfNotPresent
    ipam:
      mode: kubernetes
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
```

Method 2 to active Hubble (CCNP on all nodes):

``` 
 - fromEndpoints:
    - matchLabels:
        k8s-app: hubble-relay
    toPorts:
    - ports:
      - port: "4244"
        protocol: "TCP"
```

**Comment by rolinh** [comment]
Hi 👋 

> I active Hubble by changing policyAuditMode to 'true'

I think you're conflating two issues here: Hubble and network policies. From what you're describing, it seems you're missing a policy to allow traffic to coredns.
Note that Hubble Relay works as it doesn't need to query coredns, it gets the list of nodes to connect to by IP from Cilium itself.

**Comment by bashilias** [comment]
@rolinh 
I was talking about the traffic from coredns are being dropped:

```
[ERROR] plugin/errors: 2 redacted.com AAAA: unreachable backend: no upstream hosts available
[ERROR] plugin/errors: 2 redacted.com A: unreachable backend: no upstream hosts available
[ERROR] plugin/errors: 2 google.com A: unreachable backend: no upstream hosts available

```

I do have CCNP's dat allow traffic from and to coredns, I even replaced it with a CCNP that allows everything:
```

apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-all-egress-from-pods
spec:
  endpointSelector: {}  # Applies to all pods
  egress:
  - toEntities:
    - all
```

But unfortunately that's isnt working either.
