### ISSUE TITLE
hubble-relay pods are not starting if hubble.listenAddress is set to 127.0.0.1:4244

### ISSUE THREAD

**Issue by lirtistan** [cilium/hubble#1663]
***Bug Description:***

If i deploy cilium (via helm) and set `hubble.enable=true` and `hubble.listenAddress=127.0.0.1:4244`, the `hubble-relay` pods are not able to get ready.

I want to set the IP to limit the potential attck surface on our nodes, most of them have 2 NICs, one for INET traffic and the other NIC for LAN traffic. Actually i see no way to prevent hubble from listening on every addresses.

The only way i have is to set the host firewall, which can be challenging (many different host configurations, so not every node has an equal configuration).

My actual test deployments (K3s) are on a staging cluster (just 2 nodes), with an Debian 12 minimal setup.

This is how my actual `values.yaml` look like..
```yaml
k8sServiceHost: cluster  # a VIP behind a record in /etc/hosts
k8sServicePort: 6443
kubeProxyReplacement: true
identityAllocationMode: kvstore
etcd:
  enabled: true
  ssl: false
  endpoints:
  - http://172.16.0.1:2379
  - http://172.16.0.2:2379
updateStrategy:
  rollingUpdate:
    maxUnavailable: 1
operator:
  replicas: 2
  rollOutPods: true
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 50%
  prometheus:
    enabled: false
ipam:
  operator:
    clusterPoolIPv4MaskSize: 24
    clusterPoolIPv4PodCIDRList:
    - 10.42.0.0/16
hubble:
  enabled: true
  #listenAddress: "127.0.0.1:4244"
  metrics:
    enabled: []
  relay:
    enabled: true
    rollOutPods: true
    replicas: 2
    prometheus:
      enabled: false
envoy:
  prometheus:
    enabled: false
prometheus:
  enabled: false
```
