### ISSUE TITLE
Fail to deploy Hubble from branch v0.6

### ISSUE THREAD

**Issue by carlosjgp** [cilium/hubble#288]
From your change logs
https://github.com/cilium/hubble/blob/v0.6/CHANGELOG.md

```
adjust dockerfile and makefile for "serve" command removal (#263, @Rolinh)
```
https://github.com/cilium/hubble/pull/263/files

Output from the container
```
unknown command "serve" for "hubble"                                                                                                             
Did you mean this?                                                                                                                               
        observe     
````

Helm values
```
image:
  tag: v0.6.0
  pullPolicy: IfNotPresent

metrics:
  enabled:
    - dns
    - drop
    - tcp
    - flow
    - port-distribution
    - icmp
    - http

ui:
  enabled: true
  image:
    tag: v0.6.0
    pullPolicy: IfNotPresent

ingress:
  enabled: true
...
```

Rendered Daemonset
```
- apiVersion: apps/v1
  kind: DaemonSet
...
        containers:
        - args:
          - serve
          - --listen-client-urls=0.0.0.0:50051
          - --listen-client-urls=unix:///var/run/hubble.sock
          - --metrics-server
          - :6943
          - --metric=dns
          - --metric=drop
          - --metric=tcp
          - --metric=flow
          - --metric=port-distribution
          - --metric=icmp
          - --metric=http
          command:
          - hubble
          env:
          - name: HUBBLE_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: HUBBLE_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          image: quay.io/cilium/hubble:v0.6.0
          imagePullPolicy: IfNotPresent
          name: hubble
...
```
