### ISSUE TITLE
Failed to create gRPC client connection to peer

### ISSUE THREAD

**Issue by Antiarchitect** [cilium/hubble#312]
level=warning msg="Failed to create gRPC client connection to peer some.dns.node.name" address="192.168.202.52:4244" dial timeout=5s error="context deadline exceeded" subsys=hubble-relay

Using Cilium 1.8.1, Hubble enabled:
```
  enabled: true
  global:
    hubble:
      enabled: true
      metrics:
        enabled:
        - dns:query;ignoreAAAA
        - drop
        - tcp
        - flow
        - port-distribution
        - icmp
        - http
      relay:
        enabled: true
      ui:
        enabled: true
```

But hubble-relay tries to connect not through k8s internal address but to node internal IP which is true IP in my private network.
