### ISSUE TITLE
Apllying http-visibility breaks OAuth requests

### ISSUE THREAD

**Issue by pandarun** [cilium/hubble#588]
Hello, after applying http-visibility 

```

apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: http-visibility
spec:
  endpointSelector:
    matchLabels: {}
  ingress:
    - fromEntities:
        - all
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
          rules:
            http:
              - {}
    - fromEntities:
        - all
```

as described in [docs](https://github.com/cilium/hubble/blob/v0.5/Documentation/http_visibility.md) makes my services return 401 responses after authorization.

How can I check envoy doesn't trim Authorization headers or Cookies. 

NOTE:
If I remove the policy everything works as expected.

Any help is appreciated.
