### ISSUE TITLE
hubble-relay Failed to create peer client for peers synchronization; will try again after the timeout has expired" error="context deadline exceeded" subsys=hubble-relay target= "hubble-peer.kube-system.svc.cluster.local:4254"

### ISSUE THREAD

**Issue by nmnellis** [cilium/hubble#739]
Im running k3d on ubuntu and cilium installs and works as expected but hubble-relay does not seem to connect.

* How i installed it
```sh
  helm install cilium cilium/cilium --version  \
      --namespace kube-system \
      --set hubble.relay.enabled=true \
      --set hubble.metrics.enabled="{dns,drop,tcp,flow,icmp,http}" \
      --set hubble.ui.enabled=true \
      --set hubble.relay.dialTimeout=5s \
      --set hubble.relay.retryTimeout=5s \
      --set monitor.enabled=true \
      --set cluster.name="cluster1" \
      --kube-context $name \
      --wait
```

* log errors

```sh
level=warning msg="Failed to create peer client for peers synchronization; will try again after the timeout has expired" error="context deadline exceeded" subsys=hubble-relay target=
"hubble-peer.kube-system.svc.cluster.local:4254"                                                                                                                                      
level=warning msg="Failed to create peer client for peers synchronization; will try again after the timeout has expired" error="context deadline exceeded" subsys=hubble-relay target=
"hubble-peer.kube-system.svc.cluster.local:4254"
```

* I am able to hit this endpoint from other pods though
```
▶ k run --context cluster1 -it t14 --rm=true --image=nginx --restart=Never -- bash
+ kubectl run --context cluster1 -it t14 --rm=true --image=nginx --restart=Never -- bash
If you don't see a command prompt, try pressing enter.
root@t14:/# curl hubble-peer.kube-system.svc.cluster.local:4254
<!doctype html><html><head><meta charset="utf-8"/><title>Hubble UI</title><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="viewport" content="width=device-width,user-scalable=0,initial-scale=1,minimum-scale=1,maximum-scale=1"/><link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png"/><link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png"/><link rel="shortcut icon" href="favicon.ico"/><script defer="defer" src="/bundle.main.3b2369adf2e0c02229aa.js"></script><link href="/bundle.main.9cd671817b2cf4a1a838.css" rel="stylesheet"></head><body><div id="app"></div></body></html>
```

* K3d setup

```yaml
apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: cluster1 # name that you want to give to your cluster (will still be prefixed with `k3d-`)
servers: 1 # same as `--servers 1`
agents: 1 # same as `--agents 2`
image: rancher/k3s:v1.21.3-k3s1
network: k3d-cluster-network
ports:
  - port: 8080:80 # same as `--port '8080:80@loadbalancer'`
    nodeFilters:
      - loadbalancer
  - port: 8443:443 # same as `--port '8443:443@loadbalancer'`
    nodeFilters:
      - loadbalancer
  # hubble port
  - port: 4244:4244 # same as `--port '8443:443@loadbalancer'`
    nodeFilters:
      - loadbalancer
registries: # define how registries should be created or used
  use:
    - k3d-registry.localhost:12345
options:
  k3d: # k3d runtime settings
    wait: true # wait for cluster to be usable before returining; same as `--wait` (default: true)
    timeout: "60s" # wait timeout before aborting; same as `--timeout 60s`
    disableLoadbalancer: false # same as `--no-lb`
  k3s: # options passed on to K3s itself
    extraArgs: # additional arguments passed to the `k3s server` command; same as `--k3s-server-arg`
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      # https://sandstorm.de/de/blog/post/running-cilium-in-k3s-and-k3d-lightweight-kubernetes-on-mac-os-for-development.html
      - arg: --disable-network-policy
        nodeFilters:
          - server:*
      - arg: --flannel-backend=none
        nodeFilters:
          - server:*
      - arg: --node-taint=node.cilium.io/agent-not-ready=true:NoSchedule
        nodeFilters:
          - server:*
    nodeLabels:
      - label: topology.kubernetes.io/region=us-east-1 # same as `--k3s-node-label 'foo=bar@agent:1'` -> this results in a Kubernetes node label
        nodeFilters:
          - agent:*
      - label: topology.kubernetes.io/zone=us-east-1a # same as `--k3s-node-label 'foo=bar@agent:1'` -> this results in a Kubernetes node label
        nodeFilters:
          - agent:*
  kubeconfig:
    updateDefaultKubeconfig: true # add new cluster to your default Kubeconfig; same as `--kubeconfig-update-default` (default: true)
    switchCurrentContext: false # also set current-context to the new cluster's context; same as `--kubeconfig-switch-context` (default: true)
```

```sh
  k3d cluster create --wait --config cluster1.yaml

  # https://github.com/cilium/cilium/issues/18675
  # Mount the BPF file system in the k3s docker containers
  docker exec -it k3d-$name-agent-0 mount bpffs /sys/fs/bpf -t bpf
  docker exec -it k3d-$name-agent-0 mount --make-shared /sys/fs/bpf

  docker exec -it k3d-$name-agent-0 mkdir -p /run/cilium/cgroupv2
  docker exec -it k3d-$name-agent-0 mount none /run/cilium/cgroupv2 -t cgroup2
  docker exec -it k3d-$name-agent-0 mount --make-shared /run/cilium/cgroupv2/

  # this needs to be done for every container (every agent and every server)
  docker exec -it k3d-$name-server-0 mount bpffs /sys/fs/bpf -t bpf
  docker exec -it k3d-$name-server-0 mount --make-shared /sys/fs/bpf

  docker exec -it k3d-$name-server-0 mkdir -p /run/cilium/cgroupv2
  docker exec -it k3d-$name-server-0 mount none /run/cilium/cgroupv2 -t cgroup2
  docker exec -it k3d-$name-server-0 mount --make-shared /run/cilium/cgroupv2/
```
