### ISSUE TITLE
ExternalName k8s Services - Hubble display

### ISSUE THREAD

**Issue by Stolr** [cilium/hubble#827]
Hi ,

I'm having some issue trying to display external services.

Here are the details : 

I have an external service defined as follow : 

```yaml
kind: Service
apiVersion: v1
metadata:
  name: "searchmaster"
  labels:
    ressourcetype: service-solr-cd
    env: cd
spec:
  type: ExternalName
  externalName: searchmaster.mydomain.local 
  ```

Now , I have a pod that call this service , and also call a MysqL url ( which is not defined as a kubernetes service ). So basically configuration is :

`searchMasterUrl: http://searchmaster:8080`
`mySqlUrl: np-mysql01.mydomain.local`

Here is what I see in hubble : 

![image](https://user-images.githubusercontent.com/3446318/208852758-9a31e582-29cd-4198-87de-9b411bd2d789.png)

I can see dns resolution works because i can see  the the ip in the hubble log. But this is flag as "World"

![image](https://user-images.githubusercontent.com/3446318/208853312-a8a05ced-af47-4553-96ab-0d75d281ccc0.png)

Is there any way I can display my externalService name to identify theses flows ? 

I might missunderstanding something maybe because this should work out of the box since I use a dns name and it should get caught by dns rule.

### Cilium Version
v1.12.4

### Kernel Version
5.10.0-14-amd64

### Kubernetes Version
v1.25.4

###  Hubble version
v1.12.4

Thanks for your help !

Regards
